### ISSUE TITLE
Registering multiple custom sampler2D textures for GLSL

### ISSUE THREAD

**Issue by pilwon** [Famous/engine#150]
![glslio](https://cloud.githubusercontent.com/assets/61540/7756466/68d4883a-ffc9-11e4-82db-2341d6cdd0d6.gif)

(I was able to port some transitions from [glsl.io](https://glsl.io/) with minimal code change. Thanks @zackbrown for the code snippet :+1:)

What's the best way to register multiple textures populating `u_textures[]`? I passed image materials to `options.inputs` as a workaround because current `compileMaterial()` traverses and ensures textures in inputs are registered, but I don't think this is the intended way to do it.

Could you allow us define multiple custom `sampler2D`s and provide an API to manipulate them?

**Comment by TheAlphaNerd** [comment]
@pilwon should we move this to a conversation on slack? Perhaps we can make a gl channel

**Comment by pilwon** [comment]
@TheAlphaNerd Why? Isn't Github issue the best place for users of an open source project to discuss things like this and track it? (also, @zackbrown asked me to open this issue)

**Comment by TheAlphaNerd** [comment]
I was on cruise control. I thought this was a discussion about using glsl stuff, rather than a discussion about api changes.

**Comment by redwoodfavorite** [comment]
Hey @pilwon.  Good question.

The best way to do this is to use multiple expressions in your material, each having a $TEXTURE.  The WebGLRenderer should automatically decide what texture slot a give texture will belong to.

For example, here's a material that mixes two images based on a constant value 0.5.

```
var mixedMaterial = Material.mix(
    [
        Material.image([], { texture: 'someImage1.png' }),
        Material.image([], { texture: 'someImage2.png' }),
        0.5
    ]
);
```

If you look at the glsl for Material.image you can see it uses a $TEXTURE.  This is replaced by the WebGL renderer to automatically apply the right u_Texture[] to the shader code.

**Comment by adnan-wahab** [comment]
I'll add a section to the materials docs to make this more obvious. Thanks Pilwon.

**Comment by pilwon** [comment]
@redwoodfavorite @adnan-wahab Thanks- Adding a section to the doc sounds great.

**Comment by pilwon** [comment]
@redwoodfavorite Doesn't `Material.mix` let you only access a single (already mixed) texture from glsl? To build apps like the above example I'd need to access two separate textures and `mix()` them from the shader. Would it be possible to define custom sampler2Ds variables instead of using pre-defined `u_textures`?

**Comment by redwoodfavorite** [comment]
@pilwon In the above example each one of those 'Material.image()' are seperate materials each using their own u_Texture slot,  so by this means you should be able to bind and mix these two textures using the resulting material.  Is that what you were seeking?

I think a lesson on this stuff would be extremely valuable as well.  :+1:

**Comment by pilwon** [comment]
@redwoodfavorite Thanks! I finally figured out how to do it properly without hacks.

It turns out I was confused about the `Material.mix` example because it wasn't clear how to mix two textures with *non-*constant values. However, looking at the code where it registers `mix` expression really helped me understand how `Material` expression works.

My code looks like this:

```js
Material.registerExpression('magic', {
  defines: `
vec4 magic(vec4 img1, vec4 img2) {
  float computedValue = computeValue(v_textureCoordinate);
  return mix(img1, img2, computedValue);}
`,
  glsl: 'magic(%1, %2);',
  output: 4
});

const material = Material.magic([
  Material.image([], {texture: 'img1.jpg'}),
  Material.image([], {texture: 'img2.jpg'})
], {
  uniforms: {
    u_progress: 0
  }
});
```

**Question:** Shouldn't we worry about function name collisions here for those declared by `defines`?

**Comment by redwoodfavorite** [comment]
@pilwon It's a good point but because defines (for the time being) is any arbitrary chunk of shader code it might be hard to handle.

The material class tries to do a lot and definitely needs some API revisions.  As you get familiar with it I'd like to know what you think can be simplified/ made clearer.

**Comment by pilwon** [comment]
@redwoodfavorite I think overall it's already pretty solid and powerful the way it is. I will make sure I hit that `New Issue` button whenever I find ways to improve :v:

As for avoiding collisions, I was thinking maybe we could somehow run the user defined code through [glslify](https://github.com/stackgl/glslify) internals. The latest version of `glslify` adds suffix (ex: `_1_2`) to each function imported. We could probably apply similar technique to `Material.registerExpression()`.
