### ISSUE TITLE
material.setUniform() does not queue invalidations for Mesh

### ISSUE THREAD

**Issue by pilwon** [Famous/engine#151]
`material.setUniform()` does not seem to queue invalidations for the `Mesh`.

I discovered this while playing with GLSL transitions (re: #150), and it required me to manually invalidate mesh to redraw frame during transition when `.setRotation()` was not called on the node.

**Comment by redwoodfavorite** [comment]
Definitely a bug, working on it now.

**Comment by michaelobriena** [comment]
@redwoodfavorite Can you update on the progress?

**Comment by adnan-wahab** [comment]
Should be fixed in next release

**Comment by FarhadG** [comment]
I believe @adnan-wahab has implemented and fixed this. Looking forward to hearing the progress and its merge date.

@michaelobriena @redwoodfavorite

**Comment by alexanderGugel** [comment]
fixed in 4648641e47f068b04fd7f2b48b949823a330e7f2
