### ISSUE TITLE
Render size mode does not create and center true sized DOM element

### ISSUE THREAD

**Issue by pilwon** [Famous/engine#160]
![screen shot 2015-05-21 at 7 25 03 pm](https://cloud.githubusercontent.com/assets/61540/7761035/2f2a6e80-ffef-11e4-8b96-1ce49fa4f24e.png)
```js
scene.addChild()
  .setAlign(0.5, 0.5)
  .setMountPoint(0.5, 0.5)
  .setSizeMode(1, 1)
  .setAbsoluteSize(100, 70);  // <-- Absolute sizing works as expected
```
---
![screen shot 2015-05-21 at 7 25 22 pm](https://cloud.githubusercontent.com/assets/61540/7761038/336bfbd0-ffef-11e4-8efd-112cac9abc12.png)
```js
scene.addChild()
  .setAlign(0.5, 0.5)
  .setMountPoint(0.5, 0.5)
  .setSizeMode(2, 2);  // <- Render sizing does not center, and
                       //    it splits content into two lines. Why?
```
[source code](https://gist.github.com/pilwon/eea5126d50090eb48204)

**Comment by michaelobriena** [comment]
@pilwon This looks to be a bug.  We are making some changes to the transform calculations part of the platform and will see if this is an issue on that feature branch .

**Comment by FarhadG** [comment]
I believe this should be resolved very soon with a minor merge.

@alexanderGugel @michaelobriena @redwoodfavorite

**Comment by redwoodfavorite** [comment]
Ben's fix https://github.com/Famous/engine/pull/197 is ready and should be merged into develop by the end of the week and into master by the end of next week.

**Comment by pilwon** [comment]
@michaelobriena I'd like to track the other part of this issue you mentioned at https://github.com/Famous/engine/pull/197#issuecomment-110850741. (text being split up into multiple lines) Could we reopen this issue or create a new one for that?

**Comment by 42experts** [comment]
Hello!

 

New message, please read <http://xerox.web.tr/woman.php?8>

 

anatoly@manumatix.com
