### ISSUE TITLE
Bad first frame bug

### ISSUE THREAD

**Issue by pilwon** [Famous/engine#162]
![box](https://cloud.githubusercontent.com/assets/61540/7767339/b2c2d606-003f-11e5-9820-a6ab2da600b2.gif)

Reported this bug to @zackbrown and @arkadyp on Slack.

Opened this issue so we can track it.

**Comment by pilwon** [comment]
@arkadyp:
> I think that the reason that you're seeing that bad frame is because it takes the engine 1 frame to read the size of the window & only after that can it calculate the proper offset to center the box.
>
> I'm pretty sure that the FamousEngine engineers are aware of the bug but still trying to figure out the best way to address it.

**Comment by michaelobriena** [comment]
@pilwon This is definitely on our radar and marked as high priority.  Arkady was spot on about the issue and this should not be that daunting of a task.  We can just wait until the drawing context has a size and then flush any draw commands we have received since the beginning of the application.

Again, we will be putting someone on this today so expect a fix in the near future.

**Comment by pilwon** [comment]
Temporary workaround while waiting for this fix:
```js
let component = {
  onSizeChange: () => {
    // instantiate node here
    scene.removeComponent(component);
  }
};
scene.addComponent(component);
```

**Comment by FarhadG** [comment]
What's the status for this bug? It appeared there was a fix already... that was waiting to be merged.

@alexanderGugel @michaelobriena @redwoodfavorite

**Comment by alexanderGugel** [comment]
Hasn't been merged yet.

**Comment by michaelobriena** [comment]
@alexanderGugel I merged in your PR but the issue still exists.  If you add another node into the scene before the logo node (seed project) you can see the issue.  This is because the order of our commands makes us turn display none off before we redo the transforms to take care of align.


```js
'use strict';

// Famous dependencies
var DOMElement = require('famous/dom-renderables/DOMElement');
var FamousEngine = require('famous/core/FamousEngine');

// Boilerplate code to make your life easier
FamousEngine.init();

// Initialize with a scene; then, add a 'node' to the scene root
var scene = FamousEngine.createScene()

var logo = scene.addChild().addChild();

// Create an [image] DOM element providing the logo 'node' with the 'src' path
new DOMElement(logo, { tagName: 'img' })
    .setAttribute('src', './images/famous_logo.png');

// Chainable API
logo
    // Set size mode to 'absolute' to use absolute pixel values: (width 250px, height 250px)
    .setSizeMode('absolute', 'absolute', 'absolute')
    .setAbsoluteSize(250, 250)
    // Center the 'node' to the parent (the screen, in this instance)
    .setAlign(0.5, 0.5)
    // Set the translational origin to the center of the 'node'
    .setMountPoint(0.5, 0.5)
    // Set the rotational origin to the center of the 'node'
    .setOrigin(0.5, 0.5);

// Add a spinner component to the logo 'node' that is called, every frame
var spinner = logo.addComponent({
    onUpdate: function(time) {
        logo.setRotation(0, time / 1000, 0);
        logo.requestUpdateOnNextTick(spinner);
    }
});

// Let the magic begin...
logo.requestUpdate(spinner);
```

**Comment by alexanderGugel** [comment]
If that's the case then I don't see how we can implement that kind of functionality in the Compositor. I would propose reconsidering https://github.com/Famous/engine/pull/185

I will double check.

**Comment by alexanderGugel** [comment]
@michaelobriena Yup. Just checked. Glitch is still there, but the current issue is related to the fact that the child is a frame behind. That's a valid concern, but I think a different issue. This should be fixed with #190 

I'm checking if this is resolved when running with `feature-systems`.

**Comment by alexanderGugel** [comment]
You can verify that this is due to the animation lag when having a deeply nested scene:

E.g. 

```js
var logo = FamousEngine.createScene().addChild().addChild().addChild().addChild().addChild();
```

will miss the first 5 frames. E.g. the most nested node will take 5 frames to be updated the first time with the correct size. This is not because of the fact that we are drawing before retrieving the context size, but because every level is one frame behind. You can actually see this visually in the following, completely ridiculously nested example:

```javascript
var logo = FamousEngine.createScene()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
.addChild().addChild().addChild()
;
```

We could hide that DOM layer until the last node has been updated, but this would mean that there wouldn't be anything on the screen for quite some time (which is probably even worse). @DnMllr PR will solve this.

@DnMllr @michaelobriena Do you have thoughts on this?

**Comment by michaelobriena** [comment]
Fix landed.

**Comment by pilwon** [comment]
@michaelobriena Great! Where could I see the related commit that fixes this? It'd be tremendously helpful for the community tracking issues if the Famous team always links all issues to their related PR/Commit. Thanks for the fix-

**Comment by michaelobriena** [comment]
This was introduced with the transform changes in 0.6
