### ISSUE TITLE
All demos on website are black

### ISSUE THREAD

**Issue by esprehn** [Famous/engine#164]
On my OnePlus phone with Chrome 42 all the demos paint only black. Lots of reports on hacker news too.

https://news.ycombinator.com/item?id=9586913

**Comment by michaelobriena** [comment]
@esprehn Thanks for the heads up.  We will look into this.

**Comment by michaelobriena** [comment]
Someone at the company has a OnePlus and the site was working fine work him.  I will ask what browser he was using.

**Comment by michaelobriena** [comment]
@zackbrown What browser were you using?

**Comment by esprehn** [comment]
It's not just OnePlus, lots of reports of black on hacker news on various phones.

**Comment by Nefry** [comment]
@michaelobriena @zackbrown 
I saw the same issue on Linux machine for WebGL demo on the website: it's just not working, black view. 
It is Linux + Chrome + WebGL + Graphics + drivers problem, and  _it works in Firefox_ on the same machine.

To provide more feedback for users we could have error screen with "WebGL is disabled/ not supported" etc. [Actual lines of code] (https://github.com/Famous/engine/blob/master/webgl-renderers/WebGLRenderer.js#L71-73) that error: ```this.getWebGLContext(this.canvas)``` returns ```false```, so all code below is unable to run.

Test system:
Processor: Intel® Core™ i7-4800MQ CPU @ 2.70GHz × 8 
Graphics: GeForce GTX 765M/PCIe/SSE2
Ubuntu 14.04 LTS.
Browser Chrome (latest): Version 43.0.2357.81 (64-bit)

**Comment by FarhadG** [comment]
Thanks for filing this. I'll be looking into this, very soon.

@redwoodfavorite

**Comment by FarhadG** [comment]
I haven't been able to replicate this, however, I'm still wondering whether GPU qualifications are the issue: certain GPUs are blacklisted with various versions of browsers.

Here are simple attempts that may be helpful:

`Chrome`
optirun google-chrome-unstable --enable-webgl --ignore-gpu-blacklist

`FireFox`
Type `about:config` in Firefox’s address bar and make the following changes:
To enable WebGL, set `webgl.force-enabled` to `true`.
To enable Layers Acceleration, set `layers.acceleration.force-enabled` to `true`.
To enable Direct2D in Windows Vista/7, set `gfx.direct2d.force-enabled` to `true`.

Please refer to these resources to check whether your desktop meets the requirements:
- <a target="_blank" href="https://www.khronos.org/webgl/wiki/BlacklistsAndWhitelists">Khronos Group lists</a>
- <a target="_blank" href="https://code.google.com/p/chromium/codesearch#chromium/src/gpu/config/software_rendering_list_json.cc
">Requirements in JSON</a>

**Comment by redwoodfavorite** [comment]
Are you guys sure that it's a WebGL issue?  It sounds like @esprehn was having issues with even the DOM demos which leads me to think it's something else...

**Comment by FarhadG** [comment]
It's very much possible that the demos were overloading the resources, as many of comments had to do with the demos being slower (as they're running simultaneously).

Please confirm by checking your GPU requirements and running an app locally.

**Comment by michaelobriena** [comment]
All demos seem to be working.  Closing as this is not related to the codebase.
