### ISSUE TITLE
DynamicGeometry renders different results in Web Workers

### ISSUE THREAD

**Issue by pilwon** [Famous/engine#165]
`DynamicGeometry` renders different results in Web Workers.

---

### :-1: Triangles with 3 vertices
```js
new DynamicGeometry()
  .setVertexPositions([
    -1, 0, 0,
    1, 0, 0,
    0, 1, 0,
  ]);
```
![1](https://cloud.githubusercontent.com/assets/61540/7769592/17ce0530-0053-11e5-996b-a54b5d2f0d58.png)

---

### :+1: Triangles with 4 vertices
```js
new DynamicGeometry()
  .setVertexPositions([
    -1, 0, 0,
    1, 0, 0,
    0, 1, 0,
    0, -1, 0,
  ]);
```
![2](https://cloud.githubusercontent.com/assets/61540/7769590/17c9b9bc-0053-11e5-8775-a0945a2ac4f7.png)

---

### :-1: Lines with 0 vertices
```js
new DynamicGeometry()
  .setDrawType('lines');
```
![3](https://cloud.githubusercontent.com/assets/61540/7769591/17ca5818-0053-11e5-8078-2a6e093caec2.png)

---

### :-1: Lines with 2 vertices
```js
new DynamicGeometry()
  .setDrawType('lines')
  .setVertexPositions([
    -1, 0, 0,
    1, 0, 0,
  ]);
```
![4](https://cloud.githubusercontent.com/assets/61540/7769593/17d21882-0053-11e5-80a9-a1c363d920e0.png)

---

### :-1: Lines with 3 vertices
```js
new DynamicGeometry()
  .setDrawType('lines')
  .setVertexPositions([
    -1, 0, 0,
    1, 0, 0,
    0, 1, 0,
  ]);
```
![5](https://cloud.githubusercontent.com/assets/61540/7769594/17d5295a-0053-11e5-86fd-ec98f67e8242.png)

---

### :-1: Lines with 4 vertices
```js
new DynamicGeometry()
  .setDrawType('lines')
  .setVertexPositions([
    -1, 0, 0,
    1, 0, 0,
    0, 1, 0,
    0, -1, 0,
  ]);
```
![6](https://cloud.githubusercontent.com/assets/61540/7769595/17d56f14-0053-11e5-8d3c-d4f2a8d7e45c.png)

**Comment by michaelobriena** [comment]
@pilwon Thanks for the great repros.

@redwoodfavorite @adnan-wahab @FarhadG Can you please look into this?

**Comment by redwoodfavorite** [comment]
Hey @pilwon looking into this now.  My guess is that it has something to do with the require statements in the worker overiding geometry ids.

**Comment by redwoodfavorite** [comment]
@pilwon great catch, that PR should fix this issue.  It has to do with Geometry ids and browserify...

**Comment by FarhadG** [comment]
How are we doing on this PR, @redwoodfavorite?

**Comment by redwoodfavorite** [comment]
This PR is in and will be merged into next release!

**Comment by michaelobriena** [comment]
@redwoodfavorite which PR is this?

**Comment by redwoodfavorite** [comment]
https://github.com/Famous/engine/pull/188

**Comment by michaelobriena** [comment]
Thanks

**Comment by michaelobriena** [comment]
Landed
