### ISSUE TITLE
GestureHandler component blocks focus on <input/>

### ISSUE THREAD

**Issue by pilwon** [Famous/engine#167]
`GestureHandler` component blocks focus on `<input/>`. Is this an expected behavior?

---

### :+1: Without GestureHandler
```js
new DOMElement(node, {
  tagName: 'input'
});
```
![without](https://cloud.githubusercontent.com/assets/61540/7781891/e839acb2-00c9-11e5-8de1-9c408184fec1.gif)

---

### :-1: With GestureHandler
```js
new DOMElement(node, {
  tagName: 'input'
});

new GestureHandler(node).on('tap', (event) => {
  console.log(`[${event.time}] Blocked by handler!`);
});
```
![with](https://cloud.githubusercontent.com/assets/61540/7781892/e9a175b2-00c9-11e5-9bad-e6bbd1b9f8ae.gif)

**Comment by browles** [comment]
I would expect this. It is due to an internal `e.preventDefault()` on the mouse events. What are you trying to use the tap gesture for?

**Comment by pilwon** [comment]
@browles I was just playing with `GestureHandler`. No real use case yet but I wasn't sure what to expect from this example. How do I enable default after an internal `e.preventDefault()`?

**Comment by browles** [comment]
We currently lack an API to opt out of preventing default for gestures. We think this is a problem and isn't a permanent position.

However, on mobile devices it would be probably unusual to not prevent default, especially for two finger gestures. One finger tap and one finger drag are potential exceptions.

**Comment by TheAlphaNerd** [comment]
We should be careful with the use of prevent default� it will also break most screen readers :(

**Comment by FarhadG** [comment]
What's the status on the pull request? Curious of the ETA that it will be merged in...

@michaelobriena @alexanderGugel

**Comment by michaelobriena** [comment]
Closing as landed
