### ISSUE TITLE
"npm install -g famous-cli &&  famous init my-first-project" not working

### ISSUE THREAD

**Issue by Meai** [Famous/engine#169]
It downloads the project, in the browser it says: "file:///D:/Projects/engine/my-first-project/public/bundle.js Failed to load resource: net::ERR_FILE_NOT_FOUND"

then i figure "maybe i need to do npm i"

well it hangs forever there, both on windows and linux.

**Comment by TheAlphaNerd** [comment]
can you try this again and let us know if you are having the same problem. We cut a new release.


If the problem persists please make an issue on https://github.com/famous/famous-cli
