### ISSUE TITLE
where is DOMElement ?

### ISSUE THREAD

**Issue by dcsan** [Famous/engine#170]
I'm trying to get famous engine bundled up to run with meteor using famono
https://github.com/raix/Meteor-famono/issues/112#issuecomment-104847719

however `DOMElement` doesn't seem to be defined as expected:

DOMElement = require('famous/dom-renderables/DOMElement');

![image](https://cloud.githubusercontent.com/assets/514002/7782688/3b4b11b2-00d8-11e5-88d7-eb5fc966f3f2.png)

given there's a `-` in the path hierarchy, is that meant to map onto a class too?

**Comment by TheAlphaNerd** [comment]
It should be at famous.domRenderables.DOMElement

![screenshot](http://cl.ly/image/0L3w3v2S0410)

**Comment by TheAlphaNerd** [comment]
everything that has a ```-``` is camelCased in the object
