### ISSUE TITLE
Embed famous library without cloud service

### ISSUE THREAD

**Issue by nikkwong** [Famous/engine#172]
Can you include the famous library into your page directly and declare the JS in there? If not—why not?

Would love to post this question on slack, but the links to slack are broken.

Cheers.

**Comment by TheAlphaNerd** [comment]
hey nikkwong.

You can still ```npm install famous```

https://github.com/famous/engine-seed is an example project working without the cli.

You can also use a link from our CDN

http://code.famo.us/famous/0.5/famous.min.js

**Comment by nikkwong** [comment]
Thanks for the help thus far. Is it possible to embed famous onto a page without using any back end node packages—i.e. only having the CDN as a dependency?

**Comment by TheAlphaNerd** [comment]
if you include that cdn link you will be able to reference the famous global object.

**Comment by nikkwong** [comment]
Sweet! Thanks!
