### ISSUE TITLE
Sign up link for famous-community.slack.com broken on famous.org/support/

### ISSUE THREAD

**Issue by ottowt** [Famous/engine#173]
on the new famous.org/support/ page

re: "The first thing you need to do is visit **http://slack.famous.org/signup** and enter your email address to create an account."

the link is broken - there is no way to sign up..

**Comment by TheAlphaNerd** [comment]
We are aware of this and trying to get it up ASAP :smile:

**Comment by thinklinux** [comment]
It's working now :)

**Comment by joe-bader** [comment]
It's down again. Also going to https://famous-community.slack.com/signup says "This team's administrator has not enabled direct signups." :cry:
