### ISSUE TITLE
Unable to get height of window

### ISSUE THREAD

**Issue by graemefunk87** [Famous/engine#175]
This is the code I'm using, it's coming back with the width but not the height.  Is there something more I need to do?  I'm running this on an android 5.1 device.

```
var scene = FamousEngine.createScene();
var rootNode = scene.addChild();
var size = new Size(rootNode);

size.onSizeChange = function(s) {
    console.log(s);
}

FamousEngine.init();
```

**Comment by psyrendust** [comment]
Have you set the width and height of `html` and `body`?

If not you can use this:
```css
html, body {
  width: 100%;
  height: 100%;
}
```

Or you can use a css reset or normalizer.

**Comment by alexanderGugel** [comment]
Also you're overriding the Size component's `onSizeChange` method. Create a custom component instead.

```js
node.addComponent({
    onSizeChange: function(size) {
        console.log(size);
    }
});
```

**Comment by graemefunk87** [comment]
Thanks @psyrendust that took care of it
