### ISSUE TITLE
There's no way to change UNPACK_FLIP_Y_WEBGL in a texture

### ISSUE THREAD

**Issue by gregorybesson** [Famous/engine#177]
In the Texture class, these 2 lines (line 51-52) don't give the ability to pass alternate values in the options array:

    gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL, false);
    gl.pixelStorei(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL, false);

I suggest to permit these values to be changed.

This is for example mandatory to create a video texture with gl.UNPACK_FLIP_Y_WEBGL set to true in your 'sphere-inner-texture' demo if you don't want the video to be reverted.

**Comment by FarhadG** [comment]
@gregorybesson 

Thank you for the suggestion. We will be working to provide this feature with a simple API.

**Comment by gregorybesson** [comment]
Hello Farhad, how a re you doing ?

I've made a PR yesterday. You don't like it ?

**Comment by FarhadG** [comment]
Hi @gregorybesson , @redwoodfavorite  and I have reviewed the PR and it looks good.

**Comment by gregorybesson** [comment]
@FarhadG and @redwoodfavorite: this fix will make the sample of Joseph much better as the video on sphere-inner-texture.js won't be reverted anymore !
And the fix for #82 will make a perfect render on iOS retina displays.
