### ISSUE TITLE
Error when running "famous dev"

### ISSUE THREAD

**Issue by TheInvoker** [Famous/engine#179]
I am installing famo.us, and I created a project, then went into the folder and ran famous dev like it says here, but then I get an error:

Does anyone know how to fix this? (I'm on windows 7 64-bit)
Thanks

C:\Users\Me\Desktop\Apps\Messenger>famous create messenger
Seed project created at: C:\Users\Me\Desktop\Apps\Messenger\messenger

C:\Users\Me\Desktop\Apps\Messenger>cd messenger

C:\Users\Me\Desktop\Apps\Messenger\messenger>famous dev
Node Modules not yet installed, attempting to do so now.
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: spawn npm ENOENT
    at exports._errnoException (util.js:746:11)
    at Process.ChildProcess._handle.onexit (child_process.js:1053:32)
    at child_process.js:1144:20
    at process._tickCallback (node.js:355:11)

C:\Users\Me\Desktop\Apps\Messenger\messenger>

**Comment by TheAlphaNerd** [comment]
Hey @TheInvoker 

Sorry you are having so much trouble. This is a problem we are aware of and are working to fix this week!

If you would like you should probably head over to http://github.com/famous/famous-cli and create an issue there.

I also suggest hopping on our slack channel http://slack.famous.org/signup for one on one support!
