### ISSUE TITLE
FamousEngine does not destroy scenes

### ISSUE THREAD

**Issue by pilwon** [Famous/engine#182]
`FamousEngine` provides API to `createScene()` but not to `destroyScene()`. Calling `scene.dismount()` successfully removes all descendant nodes but it does not remove itself from the engine.

We need this functionality to avoid memory leaks in SPA where you often need to create/destroy scenes whenever layout changes.

**Comment by DnMllr** [comment]
@pilwon absolutely an oversight, thanks for pointing that out. We'll get to this shortly.

**Comment by FarhadG** [comment]
Do we have an update as to when this PR will be merged in?

@michaelobriena

**Comment by gadicc** [comment]
Looks like this is in :)

Should Scene.dismount() remove the Scene too?  There's some overlap, since createScene checks if an existing scene is mounted.

So we can close this and discuss at https://github.com/Famous/engine/issues/330.

**Comment by michaelobriena** [comment]
Closing as this was landed.
