### ISSUE TITLE
windows 7 install

### ISSUE THREAD

**Issue by jmcfet** [Famous/engine#184]
I am on windows 7  (ok poor me) as it is my dev platform . I try following your instructions on get-started.html. Now I have node 2.10.1 installed and step 3 fails:

Node modules not yet installed, attempting ...
events.js:85
             throw er;     //unhandled 'error' event

or this image
![famprob](https://cloud.githubusercontent.com/assets/6455567/7816959/8255189a-039f-11e5-948d-1990c60688cc.PNG)

I assume that this is the reason the src folder in a test project contains a script that does not exiist:
 <script src="bundle.js"></script>

I must be missing a key step as it is hard to believe this is released code and if so where is QA

**Comment by TusharaFernando** [comment]
+1

**Comment by alexanderGugel** [comment]
This is related to the famous command line utility.

The same issue has already been filed there: Famous/famous-cli#11

**Comment by zoneblaze** [comment]
I have to run "sudo famous dev" on my mac to get it to install the packages, might be worth mentioning on the tutorials as someone new to the Terminal and password protected might despair at this stage ; )

**Comment by elinfante** [comment]
You need to install de dependencies first:

``
npm install
``

Then run:

``
famous dev
``

**Comment by michaelobriena** [comment]
Closing this as fixes were merged into the CLI. https://github.com/Famous/famous-cli/issues/11

https://github.com/Famous/famous-cli/commit/92fbc75a0f7409c495bf75786d82baba531d9cbf

**Comment by jmcfet** [comment]
I have no idea how your merge process works but I am thinking if I do a new npm install -g famous-cli then I should pick up the changes. I tried doing this and things actually got worse as now famous command line is not found. I tried the process on a new machine and CLI installs but famous dev fails.

is there a way to unstall the cli on the first machine and do a clean start?

I am the javascript lead of a huge project where we have our own loader and am on verge of installing our loader as it works in windows. woud love to make your stuff work as we might be able to use it in a new project but seems to early.

**Comment by qd01a** [comment]
I put this together as an outline on how to run famous on any version of Windows, as I too wasted countless hours trying to figure out various nuances of how to make all the pieces work together.  The following outline should cover most issues one should face trying to run node.js and famous on a Windows PC:

must have git available from command line (https://git-scm.com/download/win)
must have npm available from command line (install latest node.js for Windows)

make sure git, nodejs modules, and npm are available from command-line (make sure the following directories are on the path; directories may slightly differ based on version of Windows or base install directories):

C:\Program Files\git\bin
C:\Program Files\nodejs
C:\Documents and Settings\Administrator\Application Data\npm

npm cache clean -f  <- force clears node.js cache, just in case
npm install famous-cli -g <- install famous-cli globally
npm install serve -g <- install serve globally (if not, launching "famous dev" will give this warning)
npm install -g <- globally install any additional dependencies that may be needed

to load a famous demo, from the directory of your choice:

famous fork twitterus-tutorial
famous fork carousel-tutorial

trouble-shooting:

npm install npm-install-missing -g <- "npm-install-missing" command-line may help fix missing dependencies

New projects now worked correctly even in the browser with the spinning famous logo (ie. "famous create myFamousProject").

However, when I tried loading the twitterus or carousel demo with "famous dev", it would not listen on port 1618.  I traced it to this line in package.json:

"dev": "npm run watch & serve public/ -p 1618" <- for Windows, have to add "start", which will launch "npm run watch" in a separate Window, allowing the next command (the port listener) to execute...

for Windows, change to:  "dev": "start npm run watch & serve public/ -p 1618"

Finally, while I could now load the "twitterus" project in my browser, I unfortunately couldn't figure out why I could only see the "Home" header and nothing more in either Chrome or Firefox.  Perhaps someone else has an idea on this one.  I found no errors on the javascript Developer Console either.

However, the carousel demo seemed to work perfectly after the above change was made to package.json!

**Comment by qd01a** [comment]
I figured out what to do to get "twitterus" working as well.  It seems the version downloaded via "famous fork twitterus-tutorial" is broken.  To get it working properly, download and unpack this file:

https://github.com/Famous/lesson-twitterus-starter-kit/archive/step-7.zip

Then add "start" to line 11 of package.json, so it should read:

"dev": "start npm run watch & serve public/ -p 1618"

Now run "famous dev" and go to your browser and it should work!
