### ISSUE TITLE
famous-container only working on document load

### ISSUE THREAD

**Issue by isaldarriaga** [Famous/engine#193]
One second after the document is loaded, https://assets-beta.famo.us/embed/embed.js doesn't convert the famous-container into the iframe.

Check plunkr (hit run / see console in dev tools)

http://plnkr.co/edit/As2ewoxhQ896ygfzDQ8N?p=preview

So injecting famous-container after ajax requests, or rendering it with a timed ngIf (as in the example) won't work.

**Comment by michaelobriena** [comment]
Hmm interesting. I will also cross file this for the famous-cli since it is more about the container.

**Comment by isaldarriaga** [comment]
Cool. Jquery used to have the live() function to solve the problem, but became deprecated and now they handle the issue inside on(). Look like is the readystatechange event the one to look at.

https://developer.mozilla.org/en-US/docs/Web/Events/readystatechange

I did try this morning to workaround the issue. No luck yet.

**Comment by alexanderGugel** [comment]
`on` and `live` are being used for event delegation. `readystatechange` is being fired as soon as the ready state of the document changes.

What you want are mutation events. Unfortunately browser support is currently lacking.

http://www.w3.org/TR/DOM-Level-2-Events/events.html#Events-eventgroupings-mutationevents

**Comment by isaldarriaga** [comment]
Alex, thank you very much for the information.

So, the following piece of code in embed.js solved the issue in chrome 43 and firefox 37:

document.addEventListener("DOMNodeInserted", function() {
            var e = document.querySelectorAll("div[data-famous-container-identifier]");
            console.log(e);
            Array.prototype.forEach.call(e, _manage.manage)
        });

http://plnkr.co/edit/pvRMMl3Sp8xrzpJ93QK5?p=info

But IE 11 is failing with a:
SCRIPT5009: 'Promise' is undefined
File: embed.js, Line: 323, Column: 13

8: [function(require, module, exports) {
        "use strict";

        function request(e) {
            return new Promise(function(r, t) {  // right here
                var o = _xhr2["default"](e, function(e, o) {
                    var u = o.statusCode,
                        s = o.body;
                    return e ? t(e) : u >= 400 ? t(e) : void r(s)
                });
                e.onprogress && (o.onprogress = e.onprogress)
            })
        } . . .

**Comment by michaelobriena** [comment]
@isaldarriaga I am going to close this since there is a corresponding issue for the CLI where this should be addressed.  If you are not ok with this let me know.
