### ISSUE TITLE
Carousel Tutorial (Unexpected end of input / bundle.js error)

### ISSUE THREAD

**Issue by elinfante** [Famous/engine#199]
Hi, 

I have forked the Carousel Tutorial following the steps from the website. Everything worked like a charm.  But what I have realised is that sometimes when I start editing the files to understand how it works I get the following error in the console:

``
Uncaught SyntaxError: Unexpected end of input    -----------------------     bundle.js:1
``

As soon as I refresh the browser everything starts working again. I do not get it all the time just randomly. 
Any idea why this could happen? 

Thanks!

**Comment by alexanderGugel** [comment]
Strange. Since refreshing the browser fixes the issue I assume that it is probably some weird browserify/ watchify issue. Can you check via `ps` if multiple instances of the dev script are running?

**Comment by michaelobriena** [comment]
@elinfante I have seen this too and I think this has to do with what Alex mentioned.  Every time I clear all processes running on that port I seem to not have the issue anymore.

**Comment by FarhadG** [comment]
Has anyone else encountered this? @elinfante, was @alexanderGugel suggestion helpful?

Lookin' forward to having this resolved.

@michaelobriena

**Comment by alexanderGugel** [comment]
Browserify bug. If you can reproduce it, it should be filed as an issue there. Otherwise this should be closed.

**Comment by Morgantheplant** [comment]
Closing this now

**Comment by elinfante** [comment]
Sorry for the late reply, I must say I get this issue every now and then, but I will try to do what Alexander suggests and I will get back to you If the problem persists.
