### ISSUE TITLE
Setting class through a DOMElement's attributes breaks famous css and causes positioning issues

### ISSUE THREAD

**Issue by musnit** [Famous/engine#203]
Try to set a DOMElement's class using something like:

    var domEl1 = new DOMElement(node1, {
        attributes: {
            class: 'my-class'
        }
    });
 
This results in the created div not having the 'famous-dom-element' class which I think it should have. This then causes all further nodes to have bugged positioning, shifted lower than they should be.

Full example of the bug (node 2 in the example is not rendered in the correct position):

    var Famous = require('famous');

    var DOMElement = Famous.domRenderables.DOMElement;
    var FamousEngine = Famous.core.FamousEngine;

    FamousEngine.init();
    var scene = FamousEngine.createScene();

    var node1 = scene.addChild();
    var domEl1 = new DOMElement(node1, {
        content: 'Hello World',
        properties: {
            fontFamily: 'Arial',
        },
        attributes: {
            class: 'erm'
        }
    });
    node1.setSizeMode('absolute','absolute');
    node1.setAbsoluteSize(300,300);
    var node2 = scene.addChild();
    var domEl2 = new DOMElement(node2, {
        content: 'whatsup',
        properties: {
            fontFamily: 'Arial',
        }
    });

**Comment by michaelobriena** [comment]
@musnit This is because you are setting the class via the attributes options.

If you use 

```js
FamousEngine.init();
var scene = FamousEngine.createScene();

var node1 = scene.addChild();
var domEl1 = new DOMElement(node1, {
    content: 'Hello World',
    classes: ['erm'],
    properties: {
        fontFamily: 'Arial',
    }
});
node1.setSizeMode('absolute','absolute');
node1.setAbsoluteSize(300,300);
var node2 = scene.addChild();
var domEl2 = new DOMElement(node2, {
    content: 'whatsup',
    properties: {
        fontFamily: 'Arial',
    }
});
```

That said, we should definitely throw an warning if you try and do that.  Thanks!

**Comment by musnit** [comment]
Yeh thanks, warning/error should be thrown :)
