### ISSUE TITLE
Weird issues with absolute positioning, movement, and DOMElement.setContent on iOS

### ISSUE THREAD

**Issue by musnit** [Famous/engine#204]
I'm working on an animation app that moves images and text around the page, and changes the text content over time. I'm noticing weird behaviour on ios. With the example below, using Safari or Chrome on an iphone5 ios8, the node stutters/lags on some setContent calls, moves in the y direction in addition to x, and changes size. This only seems to happen while the phone is tiled in landscape orientation.
 
I suppose I could work around this by using multiple DOMElements/Nodes and swapping them, rather than using setContent, but it does seem like there is a bug somewhere worth looking at.

    var Famous = require('famous');

    var DOMElement = Famous.domRenderables.DOMElement;
    var FamousEngine = Famous.core.FamousEngine;
    FamousEngine.init();
    var scene = FamousEngine.createScene();
    var node1 = scene.addChild();

    var domEl1 = new DOMElement(node1, {
        content: '0'
    });

    node1.setSizeMode('absolute','absolute');
    node1.setAbsoluteSize(600,400);
    var num = 0;
    var changer = node1.addComponent({
        onUpdate: function(time) {
            node1.setPosition(200-150*Math.cos(time / 1000), 100, 0);
            if (time % 500 > 480){
                domEl1.setContent(num);
                num++;
            }
            node1.requestUpdateOnNextTick(changer);
        }
    });
    node1.requestUpdateOnNextTick(changer);

**Comment by michaelobriena** [comment]
Setting the content of a DOMElement will always be non performant and should be done as little as possible as this triggers the browsers to do a lot of work.

I do not have access to an iphone5 right now but when I get back to the office next week I can see the ios specific issues you mentioned.

**Comment by michaelobriena** [comment]
I was not able to see anything that was specific to Famous and the performance issues seemed to be because of setting the content.  The staggering at the beginning was just because JIT compilation had not kicked it.  iOS may take longer to JIT which would cause the jumpiness you saw.
