### ISSUE TITLE
Node does not provide API to ".removeUIEvent()"

### ISSUE THREAD

**Issue by pilwon** [Famous/engine#212]
There is no public API to remove UI events after `node.addUIEvent()`.

We need someting like `node.removeUIEvent()`.

**Comment by michaelobriena** [comment]
While I think that something like this is generally promoting a bad pattern, you should just toggle it in the handler vs touching the DOM to add and remove all of the time, I think that this is definitely a feature that has some uses.

**Comment by alexanderGugel** [comment]
DOMElement would react to `onRemoveUIEvent` by sending an `UNSUBSCRIBE` event. ElementCache would then no longer `stopPropagation` on that node. Should be trivial to fix. That being said we should think about what adding an UI event even means. Maybe components should only receive events that have previously been added to the node via `addUIEvent` (kind of like a filter).

@DnMllr Thoughts?

**Comment by pilwon** [comment]
What's the best way to listen to `mouseover` event on a `<div/>`?
Is there a better way than using `node. addUIEvent()`?

**Comment by DnMllr** [comment]
`node.addUIEvent('mouseover')` is the best way to make that DOMElement listen to mouseover

I do think that we need `removeUIEvent` for completeness sake and I agree with @alexanderGugel about the potential implementation.

In regards to a filter, that isn't necessary or appropriate. If components react properly to `onAddUIEvent` messages then the only UIEvents coming into the system should be the ones that were added to the node. Given that, the node shouldn't start deciding which messages it will allow components to receive. It's always been an unopinionated forwarder of messages.

**Comment by FarhadG** [comment]
What's the status on this issue? It appears that @DnMllr made a suggestion, but curious if you found it sufficient/useful, @pilwon.

@michaelobriena @alexanderGugel

**Comment by alexanderGugel** [comment]
In #187 I introduced an UNSUBSCIBE command. If we want to add onRemoveUIEvent (I think we should), then it's just one method away. For the time being, I think this should stay open.

**Comment by anand-ma** [comment]
https://github.com/Famous/engine/blob/master/core/Node.js, in the above file i see onRemoveUIEvent

**Comment by alexanderGugel** [comment]
@anand-ma Thanks. This can be closed.
