### ISSUE TITLE
glslify out of date

### ISSUE THREAD

**Issue by TheAlphaNerd** [Famous/engine#22]
Do we want to update to 2.x?

**Comment by alexanderGugel** [comment]
#152 

Switching to (glShader +) glslify means we can easily support webpack using [`glslify-loader`](https://github.com/stackgl/glslify-loader).

**Comment by FarhadG** [comment]
@adnan-wahab is on top of this and should be resolving this with a PR soon, I believe,

@redwoodfavorite

**Comment by adnan-wahab** [comment]
FIXED
