### ISSUE TITLE
Publish to CDN (cdnjs & jsDelivr)

### ISSUE THREAD

**Issue by pilwon** [Famous/engine#241]
Famous provides pre-built engine bundle at `http://code.famo.us`, but it's impossible to match low latency and reliability performance offerings at popular CDNs such as [cdnjs](https://cdnjs.com/) and [jsDelivr](http://www.jsdelivr.com/).

Please publish `Famous/engine` to both of these CDNs to provide famous developers true freedom to work with whatever CDN they feel is most suitable for their app.

**Reference:** [CDN performance stats](https://www.cdnperf.com/)

**Comment by marklu** [comment]
We publish famo.us on our own domain for a few reasons:
1.) So we can control the quality of the end-to-end experience
2.) So we can gather better usage statistics to help us improve the system

Currently, we are using Fastly as our CDN provider, which provides similar latency and reliability levels to other top-tier CDNs.
    
Anyone is free to choose their own CDN solution if they'd like.

**Comment by pilwon** [comment]
@marklu I appreciate sharing rationale behind Famous CDN offering.

I agree Fastly is quite comparable to cdnjs/jsDelivr in terms of latency and reliability levels. I also understand the useful statistics Famous wants to capture. However from developer's perspective just a single CDN availability is sub-optimal compared to having multiple CDN options to choose from, especially when it costs nothing to publish and requires minimal effort to maintain them due to auto update features these top-tier CDNs provide.

> Anyone is free to choose their own CDN solution if they'd like.

Yeah this is the idea but unfortunately this won't happen unless Famous publishes there.

Wouldn't it be possible to publish to cdnjs/jsDeliver and still indirectly force developers to use Famous CDN? Majority of famous developers will likely to learn and copy code from [famous.org](http://famous.org) and Famous created content anyways. If there's no mention of these CDNs at all on your website and Github repository, the only developers using these CDNs will be the ones who actually really need them. That way you can still capture majority of usage stats you wanted to collect. What do you think?

**Comment by redwoodfavorite** [comment]
@marklu What's your thought on silently providing these alternatives?  Is it something we want to do?

**Comment by marklu** [comment]
We'll consider the feasibility of publishing to other CDNs, but since we already provide Famous via a top-tier CDN, that will remain the primary piece of support.

Anybody, including other CDN providers, is free to host Famous on their own if they like.
