### ISSUE TITLE
'.' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by tnedich** [Famous/engine#248]
Runing **famous dev** produces this error:

famous dev

> engine-seed@1.0.0 dev D:\Web projekti\FAMOUS\test-one
> ./bin/dev.js

'.' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\iojs\\\\node.exe" "C:\\Program Files\\iojs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dev"
npm ERR! node v1.5.0
npm ERR! npm  v2.7.0
npm ERR! code ELIFECYCLE
npm ERR! engine-seed@1.0.0 dev: `./bin/dev.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the engine-seed@1.0.0 dev script './bin/dev.js'.
npm ERR! This is most likely a problem with the engine-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./bin/dev.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls engine-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Web projekti\FAMOUS\test-one\npm-debug.log
child process exited with code 1

**OS: Win7 Ultimate , 64-bit**

**Comment by alexanderGugel** [comment]
This is related to the [engine-seed](https://github.com/Famous/engine-seed) project. Thanks for reporting this.

@wgester I submitted https://github.com/Famous/engine-seed/pull/24 . That should fix it IMO.

**Comment by alexanderGugel** [comment]
Fix landed in famous-cli https://github.com/Famous/engine-seed/commit/18923dd2823fd3da3f118affc2462127f00d79f1
