### ISSUE TITLE
Firefox rotation/perspective bug

### ISSUE THREAD

**Issue by FarhadG** [Famous/engine#251]
I noticed this bug, running Firefox `34.0.5`, however, it's perfectly fine now running `37.0.2`.

![error](https://cloud.githubusercontent.com/assets/1647596/8044601/97e218fa-0de2-11e5-8455-563abb55d9d8.gif)

Curious if we have any insights as to what may be causing it, incase others encounter the same issue.

**Comment by alexanderGugel** [comment]
I really hope this is some sort of bad joke. I have literally no idea why that would happen.

@DnMllr

**Comment by TheAlphaNerd** [comment]
Were you using an svg?

This was a known problem with svg�s and ff 34

**Comment by alexanderGugel** [comment]
Yes, this is using an svg.

**Comment by TheAlphaNerd** [comment]
svg confirmed in image

@michaelobriena and I had a minor freak out about this one when FF 34 dropped.

100% vendor bug. 100% 3D animation on the svg.

**Comment by alexanderGugel** [comment]
Yeah, ok. But why? I mean... WHY?

**Comment by DnMllr** [comment]
It looks like it is trying to maintain it's dimensions. Like we're rotating it, which means that it should be transitioning from a square to a rectangle in terms of screen space as a 2d projection. It looks like firefox is somehow trying to maintain its dimensions within a certain tolerance by scaling the image.

**Comment by FarhadG** [comment]
Awesome! I wasn't aware that Firefox `34` had issues with SVG. Closing this.
