### ISSUE TITLE
Require.js support

### ISSUE THREAD

**Issue by jussiry** [Famous/engine#254]
The new mixed mode engine don't seem to support loading with require.js anymore. Is there plan to add support (or am I just not using it right)?

**Comment by alexanderGugel** [comment]
We're going to support alternative bundlers once the glslify dependency has been removed.

See https://github.com/Famous/engine/issues/152

**Comment by jussiry** [comment]
Ok, thanks!

**Comment by hornos** [comment]
I have the same issue with jspm. Actually, glslify version 2.x has a 'process.binding is not supported' error in the graceful-fs module. If you change the dependency of Famous/engine back to glslify 1.6.0 it works. It also works with Famous/engine 0.5.2.
