### ISSUE TITLE
[bug] Adding camera to a scene causes animation to stop.

### ISSUE THREAD

**Issue by trusktr** [Famous/engine#261]
Try out this jsbin: http://jsbin.com/loqeyavoni/2/, which shows a rotating sphere, then uncomment the two camera lines and the rotation will stop working (but the update method still fires, as you see the `hello`s flying by in the console). cc: @talves

**Comment by alexanderGugel** [comment]
Definitely a bug! Thanks for reporting this! My guess is that the commands are not being interpreted correctly in the `Context`.

**Comment by trusktr** [comment]
@alexanderGugel Here's another one. Maybe the same bug? This one doesn't have the camera added, and the spinner component is added to the node instead of the scene: http://jsbin.com/bolarebase/1/edit?js,console,output

**Comment by alexanderGugel** [comment]
As pointed out on Slack by @adnan-wahab this shouldn't spin at all. You're setting it to a constant rotation. This is even weirder: http://jsbin.com/givakecowe/1/edit?html,js,output (wait til it forms an egg).

**Comment by trusktr** [comment]
Haha, yeah, what a bunch of weirdness!

**Comment by alexanderGugel** [comment]
This seems due to the fact that the scene is its own parent.

**Comment by adnan-wahab** [comment]
Fixed by latest transform changes 

http://jsbin.com/tukihavoto/edit?html,js,output

**Comment by adnan-wahab** [comment]
Fixed by latest transform changes  https://github.com/Famous/engine/pull/281

changed to latest version and doesnt rotate http://jsbin.com/tukihavoto/edit?html,js,output
