### ISSUE TITLE
isShown returns wrong value until after the first call to show() or hide()

### ISSUE THREAD

**Issue by hashemian** [Famous/engine#277]
When a node is created and added to the scene graph, initially calling isShown() on the node returns false, while the node is shown and visible. 

To test this issue, follow the steps in [Getting Started](http://famous.org/get-started.html) to create a new test project, and modify the code to print the isShown status of logo node. You will see the node is reported hidden, while its visible and spinning!

After the first explicit call to show() or hide function, the returned value is corrected.

**Comment by alexanderGugel** [comment]
You are completely right! Thanks for reporting this!

@DnMllr I think just changing the Node to be initially shown in `Node.Spec` should fix this (unless we want to assume that mounting nodes also shows them).

**Comment by michaelobriena** [comment]
@hashemian @alexanderGugel 

I actually would argue that this is the correct behavior.  You can create a subtree in space and not attach it to you scene graph.  Those nodes are not shown.  Not only are they mounted do they become shown.

**Comment by hashemian** [comment]
@michaelobriena I agree, if a node is not mounted, it should not be visible either, and hence `isShown` should return false. But in this case `isMounted` returns true, while `isShown` returns false.

What happens is creating a new `Scene` instance, already mark it as mounted [here](https://github.com/Famous/engine/blob/master/core/Scene.js#L66). And then all calls to `addChild` from the `Scene` instance will produce mounted nodes (the `onMount` is already invoked on them [here](https://github.com/Famous/engine/blob/master/core/Node.js#L566)). So the resulting node is already mounted. But still the node reports as not shown, because `show()` is not called anywhere!

I am not too familiar with famous general design, but I guess one options would be marking the Scene nodes as shown by default, by calling the `show()` function in their constructor after `onMount`  [here for example](https://github.com/Famous/engine/blob/master/core/Scene.js#L66), and then in `[Node.prototype.addChild](https://github.com/Famous/engine/blob/master/core/Node.js#L558)` if the current node is mounted and shown, we can call `show` for the new node as well.

This way all Scenes are shown by default (as they mounted by default too), and a new Node instance is shown if it's parent is shown.

**Comment by alexanderGugel** [comment]
I think there are two issues here:

1. We can not show nodes as soon as they are being mounted. Otherwise there would be no way to mount a hidden node.
2. It's unintuitive that nodes that new nodes are hidden by default.

> What happens is creating a new Scene instance, already mark it as mounted here. And then all calls to addChild from the Scene instance will produce mounted nodes (the onMount is already invoked on them here). So the resulting node is already mounted. But still the node reports as not shown, because show() is not called anywhere!

I kind of like that idea!

**Comment by hashemian** [comment]
Can't we simply follow the same pattern as mount for show as well? I mean, making Scene objects shown by default (as they are mounted by default), and making a "new" Node shown if its parent is shown.

I don't think if there will be any conflict between mount and show in this case, you still should be able to create Node instances which are not shown, but mounted.

**Comment by michaelobriena** [comment]
@alexanderGugel I disagree that it is confusing that Nodes are hidden by default.  They are not on the screen yet.  Only when they are on the screen are they not hidden.

**Comment by alexanderGugel** [comment]
@michaelobriena That's IMO already taken into account by not being mounted. E.g. if we show nodes as soon as they are being mounted, you can't mount a hidden node.

**Comment by hashemian** [comment]
@michaelobriena I am not sure I understand your point. The problem I am referring is that when the scene graph is loaded and is visible on the page, querying isMounted on all the nodes returns true and querying isShown returns false. This remains until the first call to show(), if any.

So you can easily end up having nodes **visible on the screen and mounted, but reported as hidden** (check the famous sample project for this)! I highly doubt if this is the intended behavior.

**Comment by michaelobriena** [comment]
@hashemian Sorry if I wasn't clear.  I get your point and yes you are correct.  I was commenting only on @alexanderGugel's response:

> It's unintuitive that nodes that new nodes are hidden by default.

**Comment by alexanderGugel** [comment]
> I disagree that it is confusing that Nodes are hidden by default. They are not on the screen yet. Only when they are on the screen are they not hidden.

They aren't visible because they aren't mounted, not because they are explicitly hidden.

Currently this is definitely a bug. Visible nodes return `false` in `isShown`. Showing nodes as soon as they are being mounted is not intuitive IMO, since it means you can't mount hidden nodes. I think we're going in circles here. I think just marking nodes as "shown" by default is the correct way to solve this.

@michaelobriena Can you make a final decision about that?
