### ISSUE TITLE
Disabling default context menu

### ISSUE THREAD

**Issue by zephraph** [Famous/engine#290]
Is there anyway to disable the default context menu other than setting an `oncontextmenu` attribute?

``` javascript
var workspaceElement = new DOMElement(workspace, {
  attributes: {
    oncontextmenu: 'javascript:return false;'
  }
});
```

From what I can tell, there's no handling of the `contextmenu` event at all. You have to use `mousedown` to determine if the right mouse button was clicked.

Am I missing something obvious?

**Comment by alexanderGugel** [comment]
You are correct. We are currently not handling this event type. This should be an easy fix. The contextmenu event just needs to be added to the [EventMap](https://github.com/Famous/engine/blob/master/dom-renderers/events/EventMap.js). I couldn't find a WebIDL interface spec yet.

* Spec: https://html.spec.whatwg.org/multipage/forms.html#context-menus

**Comment by zephraph** [comment]
Well, I'm not advocating for the event so much as trying to solve the problem of disabling the default context menu. According to the W3 Specs for DOM Level 3 Events [mouseup](http://www.w3.org/TR/2015/WD-uievents-20150428/#dfn-mouseup) is what's supposed to create the context menu as a default action. Perhaps just making it such that on ```mouseup``` when the default action is ```false``` the context menu is ignored? 

Regardless, I've always just interfaced with ```oncontextmenu```. I tried actually using the ```contextmenu``` event because I was expecting that to be defined, thus this issue. I'm not sure what you're referring to by Fx, but this ```contextmenu``` has [wide browser support](http://www.quirksmode.org/dom/events/contextmenu.html).

**Comment by alexanderGugel** [comment]
My bad! I was looking at the [contextmenu](http://caniuse.com/#search=contextmenu) statistics, which seem to be pretty bad. The `oncontextmenu` event by contrast seems to be widely supported.

Returning false still won't work, `preventDefault` should work fine.
