### ISSUE TITLE
No removeUIEvent?

### ISSUE THREAD

**Issue by zephraph** [Famous/engine#293]
Out of curioiusity, is there a reason that there's no removeUIEvent?

Is there any way to "unsubscribe" to a UIEvent without dismounting?

**Comment by redwoodfavorite** [comment]
@zephraph Good question.  'removeUIEvent' was recently implemented and should work on our develop branch.  Was just updated -> https://github.com/Famous/engine/pull/215 and these changes should be merged into master shortly.  Perhaps by the end of this week!

**Comment by zephraph** [comment]
Cool, thanks.
