### ISSUE TITLE
Error when asynchronously removing child on #v0.6.0

### ISSUE THREAD

**Issue by arkadyp** [Famous/engine#299]
`Uncaught TypeError: Cannot read property 'getComponents' of null` from `SizeSystem.prototype.update` after asynchronously removing a child.

See https://github.com/arkadyp/engine-seed/blob/async-children-append/src/index.js for an example of this issue.

**Comment by michaelobriena** [comment]
Initial thoughts are that we need to swap lines 113 and 114.

**Comment by DnMllr** [comment]
I'm having trouble reproducing this problem. It works fine for me.

**Comment by michaelobriena** [comment]
Code example was updated.  Should work now.

**Comment by DnMllr** [comment]
fix in pr #301

**Comment by adnan-wahab** [comment]
Confirmed fixed.
