### ISSUE TITLE
Directed event/listener framework

### ISSUE THREAD

**Issue by jd-carroll** [Famous/engine#319]
Currently the only way to broadcast an event is utilizing Node.emit().  This will walk the graph to the root scene node where the event it dispatched to all legs and all nodes.  This is not always desirable and inefficient at best.  

Each node should be able to dispatch events to all of their own children directly without notifying any other legs of the scene.  Similarly, each node should be able to "tell" their parent something directly.

The idea is to have a node/component tell their parent of some event.  Once the parent receives the event, the parent would then tell all of their children about the event.  After telling all of their children of the event, the parent would not propagate (bubble) the event any further up the scene.

**Comment by michaelobriena** [comment]
While I don't think that this behavior belongs on the core Node.  I think we could provide subclasses that can we used when needed.

The reason for not wanting to include it on the core Node is that it doesn't support any features of the rendering pipeline. Its only use is in application logic.

**Comment by jd-carroll** [comment]
The type of eventing described in this thread is available.  However the eventing framework is intended for use with DOM/GL events and not application events.  It is possible to use the eventing framework for non generated events if you really want to.
