### ISSUE TITLE
famous create [name-of-project] Error

### ISSUE THREAD

**Issue by whatisor** [Famous/engine#328]
Hello,
I am behind a proxy.
I can install famous cli, but when I run to create project. It shows error:
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: getaddrinfo ENOTFOUND code.famo.us
    at errnoException (dns.js:44:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)

Nodejs and npm can works nomally in other project.
Please help to solve it.
Thank you

**Comment by michaelobriena** [comment]
@whatisor Thanks for filing this.

I have migrated this question to the repo for the CLI tool where they are better suited to help you out.  https://github.com/Famous/famous-cli/issues/56
