### ISSUE TITLE
Size should only be asynchronous for "render" sized elements

### ISSUE THREAD

**Issue by jd-carroll** [Famous/engine#334]
When traversing the tree, each node should have its internal size updated when the sizing method is absolute or proportional.  The scene should be able to calculate the size for the node and make that size available as it updates.  The only exception is when either the node or one of its ancestors is set to "render" size mode.  In this case, the size will only be able to be calculated asynchronously.

**Comment by michaelobriena** [comment]
A node's .getSize will always return the pixel value of the node regardless of the size mode it is in.  I am sorry but I am a bit unclear on what you are looking for.

**Comment by jd-carroll** [comment]
If you request an update when the node is first mounted, and call getSize
in the onUpdate, the size returned is [0, 0, 0].

**Comment by DnMllr** [comment]
@jd-carroll I can look into this. I think that the first onUpdate gets called before size has propagated.

**Comment by jd-carroll** [comment]
@DnMllr - Thanks, the specific use case is for a scroll view where the
physics engine makes an upfront call to request updates and it needs as
much size information as it can get!

**Comment by jd-carroll** [comment]
Anyone out there still using famous at all?

**Comment by michaelobriena** [comment]
Use is a loose term
