### ISSUE TITLE
Child node is not rigid during transition

### ISSUE THREAD

**Issue by hornos** [Famous/engine#336]
Child node does not track its parent and lags behind during transition (Famous/engine@0.6.2):
```javascript
'use strict';

var DOMElement = require('famous/dom-renderables/DOMElement');
var FamousEngine = require('famous/core/FamousEngine');
var Transitionable = require('famous/transitions/Transitionable');

FamousEngine.init();

var bg = FamousEngine.createScene().addChild();
new DOMElement(bg).setProperty('background-color', 'grey');

var x = new Transitionable(0);

bg
  .setSizeMode('absolute', 'absolute')
  .setAbsoluteSize(250, 250);

var logo2 = bg.addChild();
new DOMElement(logo2, { tagName: 'img' })
  .setAttribute('src', './images/famous_logo.png')
  .setProperty('background-color', 'red');

logo2
  .setSizeMode('absolute', 'absolute')
  .setAbsoluteSize(120,120);

var position = bg.addComponent({
  onUpdate: function(time) {
    bg.setPosition(x.get());
    if(x.isActive()) {
      bg.requestUpdate(position);
    }
  }
});
bg.requestUpdate(position);

var transition = {
  duration: 3 * 1000,
  curve: 'spring'
}

x.set(400,transition);
```

**Comment by michaelobriena** [comment]
I am not seeing the behavior you are talking about.  The red logo seems glued to the top left corner for me.

**Comment by hornos** [comment]
Please check the screen recording: https://www.dropbox.com/s/53ua77gc38ksi6m/child.mov?dl=0

**Comment by DnMllr** [comment]
@hornos Thanks for the recording. I am also not able to reproduce what your screen recording shows on the latest version of the engine. What you are showing is a known bug in the pre v0.6.x version of the engine, which makes me suspicious that somehow you aren't on the current version. Can you reconfirm that you are on v0.6+ ?

**Comment by hornos** [comment]
You are right, it was an old version.Sorry for the false alarm.
