### ISSUE TITLE
node.hide() doesn't hide dom elements

### ISSUE THREAD

**Issue by monapasan** [Famous/engine#345]
See example: 
http://jsbin.com/kevadehili/1/edit?html,js,console,output
This should call onHide method on Dom element, but it doesn't.
this was removed in this commit :
https://github.com/Famous/engine/commit/4dccf4c1fad65f7aa7f9183ac755f99e21f04308#diff-20164165518dcfb14298730df6349123L760

**Comment by 42experts** [comment]
I have the same issue.  Essentially, v0.6.2 broke show/hide functionality which worked in the original release.  As a dirty workaround, I've created a function that hides or shows a node and its sub-nodes by changing its scale to 1 or 0 respectively.

**Comment by monapasan** [comment]
but what was the reason??
Should we now use dismount and mount method in order to hide elements and show elements?
so far hide() method make not much sense

**Comment by monapasan** [comment]
Could anyone please clarify the things?

**Comment by redwoodfavorite** [comment]
@DnMllr maybe you could clarify here?

**Comment by monapasan** [comment]
anyone ?? :)

**Comment by DnMllr** [comment]
@monapasan Hey, I'm sorry about the delay and thank you very much for bringing it to our attention. Somebody will be looking into this shortly.

**Comment by monapasan** [comment]
@DnMllr  Thank you for answer!
I actually was thinkig, that i just undederstood the things wrong. I am not absolutely sure, if it's an issue.

**Comment by redwoodfavorite** [comment]
This PR should solve the issue.  Thanks for pointing this out @monapasan.

**Comment by monapasan** [comment]
@redwoodfavorite  Thanks a lot!
I leave the issue open until it has been merged.

**Comment by monapasan** [comment]
Closing as this landed

**Comment by monapasan** [comment]
Closing as this landed
