### ISSUE TITLE
Exception Handling [Question or Bug]

### ISSUE THREAD

**Issue by jd-carroll** [Famous/engine#346]
What is the attitude / feeling towards exception handling?  

In the stacktrace below, the exception is thrown out of the rAF and breaks the animation loop.
```
Uncaught TypeError: Cannot read property 'length' of undefined
    _onTouchStart      @ ScrollView.js:74
    onReceive          @ ScrollView.js:391
    dispatchUIEvent    @ Dispatch.js:386
    handleWith         @ FamousEngine.js:258
    handleMessage      @ FamousEngine.js:228
    _channel.onMessage @ FamousEngine.js:81
    postMessage        @ Channel.js:112
    update             @ UIManager.js:153
    step               @ RequestAnimationFrameLoop.js:250
    loop               @ RequestAnimationFrameLoop.js:266
    _looper            @ RequestAnimationFrameLoop.js:79
```

**Comment by redwoodfavorite** [comment]
paging @DnMllr

**Comment by alexanderGugel** [comment]
We assert state where it makes sense. E.g. in DOMRenderer where we're checking if a target has been loaded etc. Eventually we're going to get rid of those assertions in a production build I think. Using try-catch in performance constrained parts of the codebase is probably not a good idea since it prevents V8 from optimizing the function.

If we really want to catch errors, we should break out `FamousEngine#step` into a separate function that wraps `FamousEngine#_update` into a try-catch IMO.

**Comment by jd-carroll** [comment]
@alexanderGugel I would agree with that, the framework should only guarantee the next frame.  It should be up to the user to implement finer control if they so choose.  

But I can also easily see the other side of the argument, where no try/catch should exist for performance reasons, so ...  Do we really want to catch errors?

**Comment by alexanderGugel** [comment]
@jd-carroll 

> Do we really want to catch errors?

Yes. At least during development. E.g. it's much more pleasant to debug the DOMRenderer if you have the `_assert` functions. If you use try-catch within a function, the function can't be optimized in V8. Nevertheless, all functions called within that function can still be optimized. The performance benefit really doesn't outweigh the lack of debugability in that case IMO.

**Comment by jd-carroll** [comment]
Closing this as a try/catch is not necessary.  If the next rAF is requested before the `Engine` updates, then next frame will still arrive even if an error is thrown out of the current.
