### ISSUE TITLE
$ deploy      deploy.js:49

### ISSUE THREAD

**Issue by MXD789** [Famous/engine#351]
$ npm install -g famous-cli
$ famous login
$ famous create myProject
$ cd myProject
$ famous deploy

/usr/local/lib/node_modules/famous-cli/lib/deploy.js:49
                results.scripts = config.scripts;
                                ^
TypeError: Cannot set property 'scripts' of undefined
    at /usr/local/lib/node_modules/famous-cli/lib/deploy.js:49:33
    at /usr/local/lib/node_modules/famous-cli/lib/project/link.js:14:13
    at /usr/local/lib/node_modules/famous-cli/res/sdk-bundle.js:5:9803
    at /usr/local/lib/node_modules/famous-cli/res/sdk-bundle.js:5:4719
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/famous-cli/res/sdk-bundle.js:5:4249)
    at IncomingMessage.EventEmitter.emit (events.js:117:20)
    at _stream_readable.js:919:16
    at process._tickCallback (node.js:419:13)

$

**Comment by TheAlphaNerd** [comment]
can you please make an issue on the cli?

--> https://github.com/famous/famous-cli

**Comment by MXD789** [comment]
Yes, I will. Thank.
