### ISSUE TITLE
Mobile performance

### ISSUE THREAD

**Issue by mutazmq** [Famous/engine#352]
When I tried scroll view of the legacy Famous version, I had performance issues and it was quite lagging.
Is there any change in this version in this regard? I see the new documentation, in contrast to the old one, has removed the extensive references to creating mobile apps.

**Comment by jd-carroll** [comment]
@mutazmq Mobile perform at the least is on par with the legacy engine.  However, I know performance will be substantially improved for mobile devices I just do not have the numbers to back that up right now.

If you want, try running the carousel tutorial on a mobile device and see how that performs.  Internally, it has all the same parts as the old scroll view.

**Comment by redwoodfavorite** [comment]
@mutazmq If you are looking for scrolling capabilities you can now utilize the browser's native scrolling by simply nesting DOM elements in the scene graph and using 'overflow: scroll-y' on the parent.   If you are building a twitter-style app with a scrollable list of tweets for example, use this method for scrolling.

However, if you are looking for a more involved scrollview, (i.e. custom physics or depth scrolling) you're going to need a 'famous scrollview', and I don't think their is an official implementation of a mixed-mode version like there was for legacy famous.

That being said I've heard good things about @xiamike's version of famous scrollview in framework.  Maybe he can provide us with something?

**Comment by redwoodfavorite** [comment]
Sorry after writing that I realized I kind of missed the point of your question.

Engine is definitively more performant on mobile than 0.3 due to a number of factors.  Scrolling in particular will perform much better on mobile using native scrolling.

**Comment by mutazmq** [comment]
@redwoodfavorite so you can't really build an app with famous if you need performant scrolling. Is this what you mean?

**Comment by mutazmq** [comment]
@jd-carroll If internally it is still the same, there is no point of trying further. Please check this [video](https://www.youtube.com/watch?v=EwkflvyEbtE)

**Comment by alexanderGugel** [comment]
The new engine encourages the use of native scrolling (as in the browser's "normal" overflow scrolling). 0.3 reimplemented scrolling using a custom ScrollView. Of course you can still integrate a custom ScrollView, such as [zynga's](https://github.com/zynga/scroller) or any other rendering-agnostic scroller.

I understand your frustration, but would ask you to share the code in question so we can see where the performance bottleneck is.

**Comment by redwoodfavorite** [comment]
@mutazmq Exactly the opposite really.  I was saying that mixed-mode allows you to utilize the native scrolling capabilites of the browser.  Which should be much faster on mobile.

Here's a code snippet of how to get scrolling without scrollviews in mixed-mode.

```
var DOMElement = require('famous/dom-renderables/DOMElement');
var FamousEngine = require('famous/core/FamousEngine');

FamousEngine.init();

var scene = FamousEngine.createScene('body');
var containerNode = scene.addChild()
    .setSizeMode('absolute', 'absolute', 'absolute')
    .setAbsoluteSize(150, 300, 0)
    .setAlign(0.5, 0.5, 0.5)
    .setMountPoint(0.5, 0.5, 0.5)

var containerEl = new DOMElement(containerNode)
    .setProperty('overflow', 'scroll');

var colors = ['red', 'white', 'blue'];

for (var i = 0; i < 40; i++) {
    var scrollItemNode = containerNode.addChild()
        .setProportionalSize(1, 0.2)
        .setAlign(0, 0.2 * i)

    new DOMElement(scrollItemNode)
        .setProperty('background-color', colors[i % 3])
}
```

**Comment by redwoodfavorite** [comment]
This method should be much better suited for the scrolling in the video you posted.  Try it out!

**Comment by jd-carroll** [comment]
@mutazmq for me to be able to comment on what is observed in the video I would have to see the code.  It is **very** likely that what you encountered has nothing to do with performance and everything to do with the `PhyscisEngine` input.

Additionally, I would need to know what version of the `Engine` you are using.  There is a pretty serious bug (#340) that substantially impacts performance if you encounter the condition.

**Comment by mutazmq** [comment]
@alexanderGugel  @jd-carroll  The demo I posted is based on the legacy famous, code is [here](https://github.com/mutazmq/test-famous)

**Comment by mutazmq** [comment]
@redwoodfavorite Thanks. Does this scrolling method work well with photos content on android? I mean if there is really long photos album to be scrolled?

**Comment by redwoodfavorite** [comment]
@mutazmq I would have to test it on more android devices but I would think so.  Also, what @alexanderGugel said is true about using existing scrolling libraries with famous engine.  So if you found an HTML5 scrollview that would be great for your use case (long list of images), it shouldn't be too hard to integrate something like that.

**Comment by mutazmq** [comment]
@redwoodfavorite I will. Thank you

**Comment by michaelobriena** [comment]
@mutazmq Our move to allow for native scrolling has solved a lot of our concerns with scrolling for the time being.

The biggest issue is that these solutions do NOT work for GL nor for things that have perspective.  We have solved the base use case but anything complicated will involve some handrolling for the time being.  We understand this is less than ideal and will be working on it but it is very evident from our research that implementing scrolling via JS is generally always less performant that the browser scrolling the content itself.

I am going to close this for now since we have a suitable solution that is as performant as mobile scrolling can be (since we do nothing).

**Comment by BodhiHu** [comment]
mark ...
