### ISSUE TITLE
Node.getTransform().local[12] === NaN

### ISSUE THREAD

**Issue by jd-carroll** [Famous/engine#356]
After a click event, I am noticing the transform is getting several `NaN` values.  I need to debug this more and see what is happening.  This is the case for both `local` and `global` transform objects.  The affected indexes are 12/13/14.

**Comment by alexanderGugel** [comment]
I don't seem to be able to reproduce this. Can you give an example? This would be a pretty serious bug meaning that the commands are not being interpreted correctly in `core/Famous.js`.

**Comment by jd-carroll** [comment]
@alexanderGugel I should have provided an example, I am at work right now but will work up an example later tonight.

**Comment by jd-carroll** [comment]
@alexanderGugel Haven't been able to come up with a reproducible example, but its definitely happening:
![image](https://cloud.githubusercontent.com/assets/1885864/8419870/54e9863c-1e8b-11e5-800e-ce0799bb69a0.png)

The capture is from a `touchstart` event where I am trying to find the position of each child of the node handling the event.

**Comment by jd-carroll** [comment]
@alexanderGugel Shucks, my fault... An array was being sent in as the `x` value when I was trying to position the elements.  What's strange is that setting the array as the `x` position only becomes an issue after the `touchstart` *and* all of the elements have been correctly positioned.

Anyways, I apologize for the false alarm.

**Comment by alexanderGugel** [comment]
@jd-carroll Passing in an array as position would explain that 12, 13, 14 are `NaN`, but the `touchstart` event still shouldn't have any effect on that...

Is the length of the array in both cases equivalent? E.g. `setPosition` would actually work if you pass in an one element array. E.g. `setPosition([1])` will work.

**Comment by jd-carroll** [comment]
In my `onUpdate` I was passing in a full length array as the first arg not the individual elements.  I think the only reason it was working is that the first pass correctly positioned everything and then after that it just didnt know what to do with them.

**Comment by alexanderGugel** [comment]
@jd-carroll Got it. Thanks.
