### ISSUE TITLE
Primitive geometry ignores options

### ISSUE THREAD

**Issue by paulsputer** [Famous/engine#357]
Mesh.setGeometry provides a parameter to pass options which all the primitive geometry types accept.  However, these are then ignored when creating a new geometry object as a new options object is passed in containing only the buffer definitions.

As a result the following line will still display a solid mesh instead of as a wire-frame mesh. 
``this.mesh = new Mesh(meshNode).setGeometry('Sphere', {type:'LINES'});``

**Comment by paulsputer** [comment]
For some reason I have a test failure with GeometryHelper.normalizeVertices 'All vectors should be within 2x2 bounding box'.  I don't see how my changes could affect that one.  Any ideas what causes this?

**Comment by redwoodfavorite** [comment]
hey @paulsputer that test failing is my fault don't worry about it.  This is an issue.  I'll look at your PR in shortly!
