### ISSUE TITLE
[Question] matrix3D and size

### ISSUE THREAD

**Issue by jd-carroll** [Famous/engine#360]
Why is the matrix3d transform no longer used for setting the size?

I know there are separate `SizeSystem`'s and `TransformSystem`'s, but I am just now realizing that they are truly independent of one another.  Was there any particular goal for this change?

*(Note: The reference to "change" refers to the legacy famous code base and none of the code in the current `engine`)*

**Comment by redwoodfavorite** [comment]
Hey @jd-carroll,

As far as I know, Famo.us has never used matrices to represent size - even in 0.3 and below.  

You are right that size and transform have been split up into separate systems.  Systems are simply operations that run on a particular set of data in the scene graph, but the concept of how these properties are carried down is the same.

Hope these clarifies a few things?

**Comment by jd-carroll** [comment]
@redwoodfavorite yeah, that's my fault, I never used the `size` on the `Surface` I was always setting `Transform.scale` etc.  Probably should have been using size, hence my confusion.

**Comment by redwoodfavorite** [comment]
Ah yea, scale would be carried down that way.

**Comment by jd-carroll** [comment]
@redwoodfavorite You mean `scale` and `size` aren't the same thing :smirk:
