### ISSUE TITLE
Duplicate Context.prototype.getRootSize

### ISSUE THREAD

**Issue by jd-carroll** [Famous/engine#361]
`Context` has duplicate `Context.prototype.getRootSize`:
- https://github.com/Famous/engine/blob/develop/renderers/Context.js#L156
- https://github.com/Famous/engine/blob/develop/renderers/Context.js#L227

**Comment by redwoodfavorite** [comment]
This is definitely an issue, could you make a PR for this issue alone?

**Comment by michaelobriena** [comment]
@jd-carroll nice catch.

**Comment by jd-carroll** [comment]
Will create a PR tonight

**Comment by jd-carroll** [comment]
This change has landed
