### ISSUE TITLE
[ Idea ] provide more details on 'scroll' UIevent

### ISSUE THREAD

**Issue by monapasan** [Famous/engine#371]
Currently no details provided on scroll UIevent. See:
http://jsbin.com/fihuhoxahi/4/edit?html,js,console,output
I think, it could be useful to proivde for instance following information: direction, velocity, delta.

**Comment by alexanderGugel** [comment]
I agree that it might be useful, but that's more or less a conceptual decision:

1. Do we want to have a completely spec complaint eventing system? E.g. currently we closely follow the W3C interface definitions when copying over the event properties. See http://www.w3.org/TR/DOM-Level-3-Events/#event-type-scroll

2. Do we want to copy over additional properties onto our "normalized events"? We would have to address browser inconsistencies in that case.

3. Do we want to add non-spec complaint, but useful properties, e.g. `direction`, `velocity`, `delta`?

I tend to agree that `direction`, `velocity` and `delta` are pretty useful, maybe we should "just add them" as properties.

Does anyone else have an opinion on that?

**Comment by jd-carroll** [comment]
Don't forget that the browser **disables javascript execution** while the scroll is happening, and the event is **sent after** the scroll has completed.

> A user agent must dispatch this event when a document view or an element has been scrolled. *This event type is dispatched after the scroll has occurred.*

http://www.w3.org/TR/DOM-Level-3-Events/#event-type-scroll

**Comment by redwoodfavorite** [comment]
Isn't this what gesture handler gives you?  A custom event object with velocity etc.?

**Comment by alexanderGugel** [comment]
While this might be useful, we should stick to the official spec for now. If you want to have those properties, you can either compute them on your own or use a component that exposes them.
