### ISSUE TITLE
PhyscisEngine Velocity Bug -- Incorrect dt

### ISSUE THREAD

**Issue by jd-carroll** [Famous/engine#382]
I am working on porting a physics component from `famous` to `engine` and I cannot get `Drag` to behave correctly.  I am trying to apply friction and drag to a single particle as in the old `Scroller`.  However, when I use the same configuration in `engine`, the elements do not scroll as expected.

Is anyone familiar with the changes between the first `famous` and the current `engine`?

**Comment by jd-carroll** [comment]
In the `PhysicsEngine` the `dt` is incorrectly scaled which breaks all velocity calculations.  (Atleast those based on the previous framework's method of calculating velocity.)
https://github.com/Famous/engine/blob/master/physics/PhysicsEngine.js#L332

There is no reason to scale the `dt` and this should be changed to:
```
var dt = step;
```

This way `dt` is consistent with the amount of time represented within the step (loop) of the `PhysicsEngine`

**Comment by jd-carroll** [comment]
@alexanderGugel @DnMllr @michaelobriena Can someone please take a look and tell me if I'm crazy!?! :smile: 

Most of the constraints will use the `dt` in their `update` but not in the `resolve` and I am not familiar enough with the constraints to figure out if this change will break them.

**Comment by browles** [comment]
The step is defined in milliseconds whereas the physics engine works in seconds. This is so that, say, a velocity of 200 in the positive x direction represents 200 pixels per second, as expected. Otherwise, that would be a velocity of 0.2, which I think would throw people off.

**Comment by michaelobriena** [comment]
@jd-carroll does @browles comment answer your question?

**Comment by jd-carroll** [comment]
It does, I may disagree and think that it is more confusing to be quoted in seconds, but it answers my question of why it was like that.  This also goes back to #368 and having a standardized mechanism to calculate the delta / velocity.

**Comment by michaelobriena** [comment]
I am on the side of @browles on this.  I think ms units is more favorable.

**Comment by michaelobriena** [comment]
Closing

**Comment by jd-carroll** [comment]
@michaelobriena The `PhysicsEngine` does **not** use ms units, it uses s units.  If you agree with ms units, please re-open.
