### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of null (fixed in devel)

### ISSUE THREAD

**Issue by gadicc** [Famous/engine#441]
Adding this just for reference :>  I've been experiencing this in some situations since 0.6, including 0.7, and haven't had a chance to track it down.  Delighted to say that from the Jul 20/21 commits on develop, this has been solved.  In case anyone else has been experiencing this.

Compositor.js:136:

```js
Compositor.prototype.handleWith = function handleWith (iterator, commands) {
    var path = commands[iterator];
    var pathArr = path.split('/');  // <--- here
    var context = this.getOrSetContext(pathArr.shift());
    return context.receive(path, commands, iterator);
};
```

**Comment by alexanderGugel** [comment]
This issue still persists when using the Mesh in some cases. The causes are incorrectly formatted commands (most of the time `WITH` is missing).

**Comment by gadicc** [comment]
Ah ok, got it, it's what you're tracking in #436 ("Mesh#onDismount is broken") and as per [comment 2](https://github.com/Famous/engine/issues/436#issuecomment-122907130) also affects `Mesh#onOpacityChange`, `Mesh#onSizeChange`, `Mesh#onTransformChange`, `Mesh#onHide, Mesh#onShow`.  Thanks!
