### ISSUE TITLE
FR: Allow one to pass an Element to DOMElement.setContent()

### ISSUE THREAD

**Issue by aprender** [Famous/engine#459]
DOMElement's reliance on text to specify the innerHTML loses lots of useful DOM functionality, for example, fine grained event handling, XPathing and various manipulations and traversals of DOM content.

To keep things lightweight, I propose that you allow one to pass an `Element` (https://developer.mozilla.org/en-US/docs/Web/API/Element) to a Famous `DOMElement`, eg:

```JavaScript
new DOMElement(node).setContent(document.createElement("div"));
```
This avoids the need to convert large slabs of HTML into a Famous render tree and retains all that DOM tree goodness.

**Comment by alexanderGugel** [comment]
This has been discussed before. Unfortunately the proposed solution won't work in a WebWorker. For now we prioritize having an environment agnostic platform.
