### ISSUE TITLE
dynamic update of DOMElement Content

### ISSUE THREAD

**Issue by amirmata** [Famous/engine#460]
I am trying to control the content of an animated DOM Element in such way:

DOMelement = new DOMElement(DOMNode)
        .setProperty('background-color', 'pink')
        .setProperty('padding', '10px')
        .setProperty('font-size', '32px')
        .setContent('<p> {{Name}}</p>');

As you've noticed, I am using {{Name}} which is controlled by an Angular module and controller.
Everything else in the page is updating but the DOM Element, which literally shows "{{Name}}". {{Name}} is controlled by $scope.

Any suggestions and comments about this issue?
Any comments on this issue!

**Comment by amirmata** [comment]
Well, it looks like it's Chrome problem, since it's working on Firefox!

**Comment by michaelobriena** [comment]
hey @amirmata it is our older version of the engine but still runs pretty well but if you want a more robust angular integration check out https://github.com/Famous/famous-angular.
