### ISSUE TITLE
[feature request] Bring back all the syncs.

### ISSUE THREAD

**Issue by trusktr** [Famous/engine#485]
From Famous 0.3. Pleeeeeease.

**Comment by michaelobriena** [comment]
GestureHandler.

**Comment by trusktr** [comment]
@michaelobriena Dragging off the edge in 0.3 works, but not in Engine.

**Comment by trusktr** [comment]
@michaelobriena How do pipe stuff like in 0.3?

**Comment by trusktr** [comment]
Piping and subscribing, and in general the highly uncoupled EventHandler, was so awesome in oh-three.

**Comment by michaelobriena** [comment]
I agree and really liked them myself.  That said, our eventing scheme was hands down the most complained about feature.  We have taken a look at an alternative and will reevaluate if we think it would add value to the platform.

**Comment by trusktr** [comment]
@michaelobriena For sure. IMHO, Famous 0.3 was my favorite eventing mechanism of all eventing mechanisms that I've tried in the web. It'd be great to have that and be able to apply it to normal DOM elements of normal HTML apps. Maybe it can be a standalone library separate from Engine, but under Famous namespace? Engine can be purely for rendering.
