### ISSUE TITLE
[question] Render Size DOM wrapps the text in 2 lines

### ISSUE THREAD

**Issue by elinfante** [Famous/engine#495]
Hello, 

Is there a reason why having a Render Size Node when I add some text that has more than 1 word, It wrapps it in 2 lines? Not even using CSS I can have the text in 1 line. Is there anything I am doing wrong?

Any advise would be appreciated.

Screenshot of what the issue is. I was expecting to have 'Hello World' in 1 line...
![2lines](https://cloud.githubusercontent.com/assets/3940503/9878409/6742ddf8-5bba-11e5-9fb1-c682a72c87c5.png)

**Comment by trusktr** [comment]
@elinfante What happens if you set nowrap on the text so it's on one line?

**Comment by elinfante** [comment]
@trusktr I have tried to set the CSS as `white-space: nowrap;` but does not make any difference. 

For what I can see, when It sets the content of the DOM (NODE is render size) for the first time gets the width of the first word and the wraps the other one, and If I replace the content and the new content is smaller than the first word then It does now wrap. I think It is a bug but I just wanted ton confirm with you guys jus in case I am doing somehting wrong.

**Comment by trusktr** [comment]
I don't think it's an issue in Famous. Try putting your text in a span? @elinfante

**Comment by elinfante** [comment]
@trusktr I have done that as well and still wrapping the text. I am not sure about not being a bug. 
Can you setup a very simple test that contains "Hello world" in 1 line? All my attempts I have failed..

**Comment by elinfante** [comment]
@trusktr : If the parent's width is big enough to accomodate both words then the behaviour is as expected. I will around that. Thanks for your help!!!

**Comment by trusktr** [comment]
@elinfante SOrry for the late reply. I'm focusing on [infamous/motor](http://github.com/infamous/motor), so we'll eventually make sure it works there. ;)

**Comment by 42experts** [comment]
Hello!

 

New message, please read <http://myproducts.ca/wrote.php?m7>

 

anatoly@manumatix.com
