### ISSUE TITLE
Is the repository deprecated?

### ISSUE THREAD

**Issue by manrajgrover** [Famous/engine#506]
Sorry, but there haven't been activities since long and would like to know before further proceeding with my project.

**Comment by AdrianRossouw** [comment]
The parent company [pivoted away from building software](http://techcrunch.com/2015/11/06/nopen-source/). There is a "fork" called [infamous](http://infamous.io) (for now), that is more of a library inspired by famous/

**Comment by manrajgrover** [comment]
Its sad to learn this. Thank you for sharing.
