### ISSUE TITLE
Proportional sizing z

### ISSUE THREAD

**Issue by redwoodfavorite** [Famous/engine#70]
It seems like using proportional size for z results in a 0 z-size.  Perhaps we could use some value like innerWidth to determine z-size...

**Comment by michaelobriena** [comment]
I don't think a z-size off the bat makes sense.  Proportional works but because everything starts as a dom element, zsize of 0 makes sense to me.

**Comment by redwoodfavorite** [comment]
Sorry for the late response.

I think that giving our scene depth would be more intuitive and more consistent with our sizing models.  Currently, if a famous user want to align or proportionally size z values, they have to add pixel depth to their scene first.  On the other hand, x and y values have starting values based on the visible bounds of the screen.

It's been suggested that we use the near and far clipping planes of our frustrum to specify our scene's z-size, and I think that makes sense considering that it specifies visible bounds of our scene.

**Comment by FarhadG** [comment]
This has been put on our radar and will be implemented as we approach our frustrum model, in the near future.

@redwoodfavorite

**Comment by michaelobriena** [comment]
@redwoodfavorite I am still a bit unsure about this.  I would want to do some use rtesting to see what was expected.

**Comment by michaelobriena** [comment]
Not in love with this idea.  We will leave as is for time being.
