### ISSUE TITLE
Support high DPI (retina) displays

### ISSUE THREAD

**Issue by pilwon** [Famous/engine#82]
Mesh nodes look blurry on my Macbook Pro w/ Retina Display.

Please support high DPI (retina) displays by handling `window.devicePixelRatio` as explained [here](https://www.khronos.org/webgl/wiki/HandlingHighDPI).

**Comment by michaelobriena** [comment]
We will definitely work towards this in the near future

**Comment by pilwon** [comment]
@michaelobriena Looking forward to this update. It'd be nice to allow overriding device pixel ratio via API. It'll allow dropping down pixel size for apps that do not require sharp rendering.

**Comment by FarhadG** [comment]
@pilwon 

I agree about the ability to change the quality. I believe the default, as it stands, is good, however, the ability to change the quality for various devices would be a great feature. We will be working on providing this feature very soon.

**Comment by gregorybesson** [comment]
@FarhadG 
Do you mean that you'll add support for high DPI soon ?
It seems I have the same problem with video as a texture on webgl spheres on my retina displays :-P

**Comment by FarhadG** [comment]
@pilwon @gregorybesson 

PR in for this request. We'll be adding the ability to change the quality of app with more control, rather than relying on the pixel density. I believe that with this ability, you can target various devices with different qualities, so you don't thrash the GPU for devices that have 2+ pixel density.

**Comment by gregorybesson** [comment]
@FarhadG 
Thx a lot ! I owe you a beer ;) 
(And if you can look at the #177 and my associated PR, I'll owe you 2 beers !)

**Comment by pilwon** [comment]
@FarhadG Thanks, looking forward to merging this PR

**Comment by michaelobriena** [comment]
Landed in https://github.com/Famous/engine/tree/v0.5.1
